account/urls.py
from django.urls import path
from . import views

app_name='account'
urlpatterns=[
    path('register/',views.UserRegisterView.as_view(),name='register'),
    path('login/',views.UserLoginView.as_view(),name='login'),
    path('logout/',views.UserLogoutView.as_view(),name='logout'),
    path('profile/<int:user_id>/',views.UserProfileView.as_view(),name='profile'),
    path('reset/',views.UserEmailReset.as_view(),name='reset_email'),
    path('reset/done/',views.UserPasswordResetDone.as_view(),name='reset_done'),
    path('confirm/<uidb64>/<token>/',views.UserPasswordResetConfirm.as_view(),name='confirm_password'),
    path('confirm/done/',views.UserPasswordResetComplete.as_view(),name='password_complete'),
    path('edit/',views.EditUserProfileView.as_view(),name='edit_profile'),

]

app/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='home')),
    path('account/', include('account.urls',namespace='account')),
]

home/urls.py
from django.urls import path
from . import views

app_name='home'


urlpatterns=[
    path('',views.HomeView.as_view(),name='home'),
    path('post/<int:post_id>/<slug:post_slug>/',views.PostView.as_view(),name='post'),
    path('post/delete/<int:post_id>/',views.DeleteView.as_view(),name='delete_post'),
    path('post/update/<int:post_id>/',views.UpdateView.as_view(),name='update_post'),
    path('follow/<int:user_id>/',views.FollowView.as_view(),name='follow'),
    path('unfollow/<int:user_id>/',views.UnFollowView.as_view(),name='unfollow'),
    path('reply/<int:post_id>/<int:comment_id>/',views.ReplyView.as_view(),name='reply_view'),
    path('like/<int:post_id>/',views.LikeView.as_view(),name='like_view'),
]

templates/app/inc/message.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/app/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-warning">
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home:home' %}">Home</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:profile' user.id %}">Profile</a>
                </li>

            {% else %}
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'account:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>